#include <acu_debug_led.h>
#include "stm32f4xx.h"
#include "gpio.h"

void led_clear_all_leds(){
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_RESET);

    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_RESET);
}

void led_set_all_leds(){
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_SET);

    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_SET);
}

void led_set_1_red() {
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_RESET);
}

void led_set_1_blue() {
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_SET);
}

void led_set_1_green() {
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_RESET);
}

void led_set_1_purple() {
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_RESET);
}

void led_set_1_white() {
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_SET);
}

void led_clear_1() {
    HAL_GPIO_WritePin(ACU_LED1_RED_GPIO_Port,ACU_LED1_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_GREEN_GPIO_Port,ACU_LED1_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED1_BLUE_GPIO_Port,ACU_LED1_BLUE_Pin, GPIO_PIN_RESET);
}

void led_set_2_blue() {
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_RESET);
}

void led_set_2_green() {
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_RESET);
}

void led_set_2_red() {
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_RESET);
}

void led_set_2_purple() {
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_RESET);
}

void led_set_2_white() {
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_SET);
}

void led_clear_2() {
    HAL_GPIO_WritePin(ACU_LED2_RED_GPIO_Port,ACU_LED2_RED_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_GREEN_GPIO_Port,ACU_LED2_GREEN_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(ACU_LED2_BLUE_GPIO_Port,ACU_LED2_BLUE_Pin, GPIO_PIN_RESET);
}



